// Include any postdeployment steps here, such as steps necessary to test that the deployment was successful. If there are no postdeployment steps, leave this file empty.

== Postdeployment steps


=== Access the {partner-product-short-name} IP address

After the stacks show a *CREATE_COMPLETE* status, you can access the {partner-product-short-name} instances through the bastion host. If you've provisioned the example application, optionally test the WAF service:


To access the parent template outputs, perform one of the following steps:
* If using the AWS Management Console, navigate to *CloudFormation > <stack name> > Outputs*.
* If using the AWS Command Line Interface (AWS CLI), run this command:
+
----
aws --region ${REGION} cloudformation describe-stacks --stack-name ${STACK_NAME}  --query  "Stacks[0].Outputs"
----

To obtain the private IP address of the {partner-product-short-name} management port, perform one of the following steps:
* If using the AWS Management Console, navigate to *CloudFormation > <stack name> > Outputs > bigipInstance01MgmtPrivateIp*.
* If using the AWS CLI, run this command:
+
----
aws --region ${REGION} cloudformation describe-stacks --stack-name ${STACK_NAME} --query  "Stacks[0].Outputs[ OutputKey=='bigipInstance01MgmtPrivateIp'].OutputValue" --output text
----

To obtain the public IP address of the bastion host, perform one of the following steps:
* If using the AWS Management Console, navigate to *CloudFormation > <stack name> > Outputs > <bastion host>*.
* If using the AWS CLI, run this command:
+
----
aws --region ${REGION} cloudformation describe-stacks --stack-name ${STACK_NAME} --query  "Stacks[0].Outputs[ OutputKey=='bastionHost'].OutputValue" --output text
----


==== SSH

From your desktop client/shell, run this command to create an SSH tunnel. Replace the variables in brackets before running the command.
----
ssh -i [keyname-passed-to-template.pem] -o ProxyCommand='ssh -i [keyname-passed-to-template.pem] -W %h:%p ec2-user@[BASTION-HOST-PUBLIC-IP]' admin@[BIG-IP-MGMT-PRIVATE-IP]
----

Example:
----
ssh -i ~/.ssh/mykey.pem -o ProxyCommand=`ssh -i ~/.ssh/mykey.pem -W %h:%p ec2-user@34.82.102.190' admin@10.0.1.11
----

==== SSH and Configuration Utility (WebUI)

To obtain the URL address of the {partner-product-short-name} management port, perform the following steps:

NOTE: Multi-NIC environments use https://host, and single NIC environments use
https://host:8443.

. From your desktop client/shell, run this command to create an SSH tunnel through the bastion host:
+
----
ssh -i [keyname-passed-to-template.pem] ec2-user@[BASTION-HOST-PUBLIC-IP] -L [DESKTOP_PORT]:[BIG-IP-MGMT-PRIVATE-IP]:[BIGIP-GUI-PORT]
----
+
Example:
+
----
ssh -i ~/.ssh/mykey.pem ec2-user@34.82.102.190 -L 8443:10.0.1.11:443
----

. In a browser, navigate to the {partner-product-short-name} user interface:
+
https://localhost:8443

NOTE: By default, the {partner-product-short-name} system’s WebUI starts with a self-signed
certificate. Follow your browser’s instructions for accepting self-signed certificates
For example, if using Firefox, select *Advanced > Accept Risk and Continue*. If using Chrome, click inside the page and type *thisisunsafe*.

Login credentials:
* User name: admin
* Password: <your-AWS-secret>

==== SSH

From TMOS Shell (tmsh), type *bash* and then press the Enter key to access the bash shell.

Examine the downloaded {partner-product-short-name} configuration file:
+
----
cat /config/cloud/runtime-init.conf
----

Examine the running {partner-product-short-name} configurations:

* https://www.f5.com/pdf/products/automation-toolchain-overview.pdf[F5
Automation Toolchain^] declarations include:
+
[source,bash]
----
curl -su admin: http://localhost:8100/mgmt/shared/declarative-onboarding | jq .
curl -su admin: http://localhost:8100/mgmt/shared/appsvcs/declare | jq .
----

* https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/[Cloud
Failover Extension^] declaration includes:
+
[source,bash]
----
curl -su admin: http://localhost:8100/mgmt/shared/cloud-failover/declare | jq .
----

==== WebUI

. If you provisioned the example application, navigate to *Virtual Services*.
. From the *Partition* menu in the upper-right corner of the screen, select *Partition =
`Tenant_1`*.
. Navigate to *Local Traffic > Virtual Servers*. You should see the virtual services for HTTP and HTTPS, with both appearing as green. Select them to look at the configuration that's declared in the
AS3 declaration.

. Navigate to *Security > Application Security*, and select the *CustomWAFPolicy* policy so you can inspect it.


=== Test the WAF service

If you've provisioned the example application, perform the following steps to test the WAF service:

[arabic]
. To obtain the address of the WAF service, perform one of the following steps:

* If using the AWS Management Console, navigate to *CloudFormation > _<STACK_NAME>_ > Outputs > applicationPublicIp*.
* If using the AWS CLI, run this command:
+
----
aws --region ${REGION}  cloudformation describe-stacks --stack-name ${STACK_NAME} --query  "Stacks[0].Outputs[?OutputKey=='applicationPublicIp'].OutputValue" --output text
----

[arabic, start=2]
. To verify that the application is responding, paste the IP address in a browser: `https://${IP_ADDRESS_FROM_OUTPUT}`

NOTE: By default, the virtual service starts with a self-signed
certificate. Follow your browser’s instructions for accepting self-signed certificates
For example, if using Firefox, select *Advanced > Accept Risk and Continue*. If using Chrome, click inside the page and type *thisisunsafe*.

* To use CURL:
+
----
curl -sko /dev/null -w '%{response_code}\n' https://${IP_ADDRESS_FROM_OUTPUT}
----

[arabic, start=3]
. Verify the WAF is configured to block illegal requests:
+
----
curl -sk -X DELETE https://${IP_ADDRESS_FROM_OUTPUT}
----

* The response should include a message that the request was blocked and a reference support ID, for example:
+
----
$ curl -sko /dev/null -w '%{response_code}\n' https://55.55.55.55
200
$ curl -sk -X DELETE https://55.55.55.55
<html><head><title>Request Rejected</title></head><body>The requested URL was rejected.
Please consult with your administrator.<br><br>Your support ID is:
2394594827598561347<br><br><a href='javascript:history.back();'>[Go Back]</a></body></html>
----


=== Test the failover

If you deployed the example application, perform the following steps to test the failover:

[arabic]
. Log in to the {partner-product-short-name} instances.
. Perform the following steps:

* If using the AWS Management Console, navigate to *Device Management of Active Instance > Traffic-Groups*, and select the box next to *traffic-group-1*. Then select *Force to Standby*.
* If using the {partner-product-short-name} command line, run this command:
+
----
tmsh run sys failover standby
----

[arabic, start=2]
. Verify that the Elastic IP address associated with the virtual service (applicationPublicIp) is remapped to the peer {partner-product-short-name} instance (for example, from 10.0.10.11 in Availability Zone 1 to 10.0.20.11 in Availability Zone 2).


[arabic, start=2]
. To verify that the application is responding:

* Paste the IP address in a browser: `https://${IP_ADDRESS_FROM_OUTPUT}`

NOTE: By default, the virtual service starts with a self-signed
certificate. Follow your browser’s instructions for accepting self-signed certificates
For example, if using Firefox, select *Advanced > Accept Risk and Continue*. If using Chrome, click inside the page and type *thisisunsafe*.

* Use CURL:
+
----
curl -sko /dev/null -w '%{response_code}\n' https://${IP_ADDRESS_FROM_OUTPUT}
----

[arabic, start=3]
. Verify the WAF is configured to block illegal requests:
+
----
curl -sk -X DELETE https://${IP_ADDRESS_FROM_OUTPUT}
----

NOTE: In this example, traffic uses Source Network Address Translation (SNAT). According to the example application, the client is the SNAT address. The real client IP is passed via the `x-forwarded-for:` header. Observe how the client IP address changes from one {partner-product-short-name} instance in one Availability Zone to the other.


== Best practices for using {partner-product-short-name} on AWS
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

// _Add any best practices for using the software._

For illustration purposes, this Partner Solution provides an option to pre-provision additional cloud resources (IP addresses)
needed for an example virtual service. However, in practice, it's designed solely to facilitate the initial deployment as cloud-init runs once. It's typically used for initial provisioning, not as the primary configuration API for a
long-running platform. More typically in an infrastructure use case,
virtual services are added after initial deployment, outside the lifecycle of this Cloudformation template.

=== Add services via the cloud
Provision additional IP addresses on the desired network interfaces. Refer to the following resources:
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/MultipleIP.html#ManageMultipleIP[Assign a secondary private IPv4 address^]
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html#using-instance-addressing-eips-allocating[Allocate an Elastic IP address^]
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html#using-instance-addressing-eips-associating[Associate an Elastic IP address with an instance or network interface^]

=== Add services via {partner-product-short-name}
Create virtual services that match the secondary IP addresses. Also update the AS3 declaration with additional virtual services. Refer to https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/composing-a-declaration.html[Composing an AS3 Declaration^] for more information.


NOTE: For cloud resources, templates can be created or customized to pre-provision
and update addtional resources (for example, various combinations of
NICs, IPs, public IPs, etc). Refer to the link:#_support[Support] section
for more information. For the {partner-product-short-name} configurations, use either REST or Automation Toolchain clients like
https://ansible.github.io/workshops/exercises/ansible_f5/3.0-as3-intro/[Ansible^] or https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_as3[Terraform^].

== Delete the deployment

Cloudformation doesn't delete S3 buckets that contain data. To delete this deployment, manually empty and/or delete the S3 bucket created for the Cloud Failover Extension (provided via the *cfeS3Bucket* parameter). In the AWS Management Console, go to S3 and search for the *cfeS3Bucket* bucket name. Select the radio button associated with the bucket and select *Empty*.

You can now delete the deployment. Still in the AWS Management Console, open Cloudformation, go to *Stacks*, and select the radio button associated with the parent stack. Finally, select *Empty*.

For more information, refer to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/troubleshooting.html[Troubleshooting AWS CloudFormation^].


== Security
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.


[arabic]
This solution requires internet access for downloading additional F5 software components used for onboarding and configuring the {partner-product-short-name} instance (via GitHub.com). Internet access is required via
the management interface and then via a dataplane interface (for
example, external Self-IP) once a default route is configured. Refer to
https://support.f5.com/csp/article/K13284[Overview of management interface routing^] for
more details. By default, as a convenience, this Partner Solution provisions
public IP addresses to enable this, but in a production environment, outbound
access should be provided by a `routed` SNAT service (for example, NAT
gateway, custom firewall, etc).

NOTE: Access via web proxy is not
currently supported. Other options include either (1) hosting the file locally
and modifying the runtime-init package URL and configuration files to
point to local URLs instead or (2) Baking them into a custom image, using
the https://clouddocs.f5.com/cloud/public/v1/ve-image-gen_index.html[F5 BIG-IP Image Generation Tool^].

Internet access is also required for contacting native cloud services (for example, s3.amazonaws.com, ec2.amazonaws.com, etc.) for various cloud integrations.

=== Onboarding
Use https://github.com/f5networks/f5-bigip-runtime-init[F5 BIG-IP Runtime
Init^] to fetch secrets from native vault services.

=== Operation

Use the following resources:

* https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/[F5 Application Services 3^] for features like Service Discovery
* https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/[F5 Telemetry Streaming^] for logging and reporting
* https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/[Cloud Failover Extension^] for updating IP addresses and route mappings

You can use additional cloud services like https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints.html[VPC endpoints^] to address calls to native services traversing the internet. See the link:#_security[Security] section for more details.

The Partner Solution's CloudFormation template downloads the following helper code to configure the
{partner-product-short-name} system:

* f5-bigip-runtime-init.gz.run: The self-extracting installer for the F5
BIG-IP Runtime Init RPM can be verified against a SHA256 checksum
provided as a release asset on the F5 BIG-IP Runtime Init public GitHub
repository, for example:
https://github.com/F5Networks/f5-bigip-runtime-init/releases/download/1.4.1/f5-bigip-runtime-init-1.4.1-1.gz.run.sha256.
* F5 BIG-IP Runtime Init: The self-extracting installer script extracts,
verifies, and installs the F5 BIG-IP Runtime Init RPM package. Package
files are signed by F5 and automatically verified using GPG.
* F5 Automation Toolchain components: F5 BIG-IP Runtime Init downloads,
installs, and configures the F5 Automation Toolchain components.
Although optional, F5 recommends adding the *extensionHash* field to
each extension installation operation in the configuration file. This field triggers verification of the downloaded component package
checksum against the provided value. The checksum values are published
as release assets on each extension’s public GitHub repository, for
example:
https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.30.0/f5-appsvcs-3.30.0-5.noarch.rpm.sha256

The following configuration file verifies the DO
and application services extensions before configuring AS3 from a local
file:

[source,yaml]
----
runtime_parameters: []
extension_packages:
    install_operations:
        - extensionType: do
          extensionVersion: 1.23.0
          extensionHash: bfe88c7cf3fdb24adc4070590c27488e203351fc808d57ae6bbb79b615d66d27
        - extensionType: as3
          extensionVersion: 3.30.0
          extensionHash: 47cc7bb6962caf356716e7596448336302d1d977715b6147a74a142dc43b391b
extension_services:
    service_operations:
      - extensionType: as3
        type: url
        value: file:///examples/declarations/as3.json
----

For more information about F5 BIG-IP Runtime Init and additional examples, refer to the https://github.com/F5Networks/f5-bigip-runtime-init/blob/main/README.md[GitHub repository^].


This template can send non-identifiable statistical information to F5 Networks to help improve templates. You can disable this functionality for this deployment by setting the value of the **allowUsageAnalytics** input parameter to *false*, or you can disable it system-wide by setting the **autoPhonehome** system class property value to *false* in the F5 Declarative Onboarding declaration. Refer to the link:#_customize_the_big_ip_ve_configuration[Customizing the BIG-IP Configuration] section for more information.


{partner-product-short-name} may contact the following list of endpoints during onboarding:

* {partner-product-short-name} image default:
** vector2.brightcloud.com (by {partner-product-short-name} image for
https://support.f5.com/csp/article/K03011490[IPI subscription validation^])

* Solution/onboarding:
** github.com (for downloading helper packages mentioned earlier)
** f5-cft.s3.amazonaws.com (downloading GPG Key and other helper configuration files)
** license.f5.com (licensing functions)

* Telemetry:

** product-s.apis.f5.com.
** f5-prod-webdev-prod.apigee.net.
** id-prod-global-endpoint.trafficmanager.net.
** global.azure-devices-provisioning.net.
** www-google-analytics.l.google.com
